// Copies the Terms of Service and Privacy Policy text from the web repo into src/legalText.ts, so the scene
// can show them in-game. Re-run after either page changes:  node scripts/buildLegalText.mjs [path-to-web-repo]
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const web = process.argv[2] ?? join(process.cwd(), '..', 'galaxy-gardeners-web')
const PAGES = [
  ['TERMS', 'terms-of-service.html', 'https://galaxygardeners.app/terms-of-service'],
  ['PRIVACY', 'privacy-policy.html', 'https://galaxygardeners.app/privacy-policy'],
]

const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ', mdash: '—', ndash: '–', rsquo: '’', lsquo: '‘', rdquo: '”', ldquo: '“', hellip: '…', copy: '©' }
function clean(html) {
  return html
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<[^>]+>/g, '')
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&([a-z]+);/gi, (m, e) => ENTITIES[e.toLowerCase()] ?? m)
    .replace(/\s+/g, ' ')
    .trim()
}

function blocks(file) {
  const html = readFileSync(join(web, 'public', file), 'utf8')
  const section = html.slice(html.indexOf('<section class="legal">'), html.indexOf('</section>'))
  const out = []
  for (const m of section.matchAll(/<(h1|h2|p|li)([^>]*)>([\s\S]*?)<\/\1>/g)) {
    const kind = m[1] === 'p' && /legal__updated/.test(m[2]) ? 'updated' : m[1]
    const text = clean(m[3])
    if (text) out.push({ kind, text })
  }
  if (out.length < 10) throw new Error(`${file}: only ${out.length} blocks found; has the page layout changed?`)
  return out
}

let ts = `// Generated by scripts/buildLegalText.mjs from galaxy-gardeners-web/public — do not edit by hand.\n` +
  `export type LegalBlock = { kind: 'h1' | 'h2' | 'p' | 'li' | 'updated'; text: string }\n` +
  `export type LegalDoc = { url: string; blocks: LegalBlock[] }\n\n`
for (const [name, file, url] of PAGES) {
  ts += `export const ${name}: LegalDoc = ${JSON.stringify({ url, blocks: blocks(file) }, null, 2)}\n\n`
}
writeFileSync(join(process.cwd(), 'src', 'legalText.ts'), ts)
console.log('wrote src/legalText.ts')
