// Generated by scripts/buildLegalText.mjs from galaxy-gardeners-web/public — do not edit by hand.
export type LegalBlock = { kind: 'h1' | 'h2' | 'p' | 'li' | 'updated'; text: string }
export type LegalDoc = { url: string; blocks: LegalBlock[] }

export const TERMS: LegalDoc = {
  "url": "https://galaxygardeners.app/terms-of-service",
  "blocks": [
    {
      "kind": "h1",
      "text": "Terms of Service"
    },
    {
      "kind": "updated",
      "text": "Last updated: September 26, 2026"
    },
    {
      "kind": "h2",
      "text": "1. Acceptance of Terms"
    },
    {
      "kind": "p",
      "text": "By downloading, installing, or using Galaxy Gardeners (\"the Game\") — in the Galaxy Gardeners iOS app or in Decentraland — you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, do not use the Game. We may update these Terms from time to time; continued use of the Game after changes constitutes acceptance of the revised Terms."
    },
    {
      "kind": "h2",
      "text": "2. Account Rules"
    },
    {
      "kind": "p",
      "text": "You may create one account per person. You are responsible for maintaining the security of your account credentials. In Decentraland, your game account is tied to the wallet you sign in with, and you are responsible for the security of that wallet. You must not share, transfer, or sell your account to another person. You must provide accurate information when creating your account. We reserve the right to suspend or terminate accounts that violate these Terms."
    },
    {
      "kind": "h2",
      "text": "3. Purchases"
    },
    {
      "kind": "p",
      "text": "The Game offers optional purchases (such as fuel and cosmetic items). In the iOS app, purchases are processed through the Apple App Store and are subject to Apple's terms and refund policies. In Decentraland, purchases are paid in MANA on the Polygon network, sent from your wallet to MetaPetal's wallet; items are credited once the transaction is confirmed on the blockchain. Blockchain transactions are final and cannot be reversed by us, and you are responsible for any network fees and for sending payment from the wallet you play with. Prices are displayed before confirmation. Virtual items and currency have no real-world monetary value and cannot be exchanged, refunded, or transferred outside the Game except as required by applicable law."
    },
    {
      "kind": "h2",
      "text": "4. User Conduct"
    },
    {
      "kind": "p",
      "text": "When using the Game, including chat and social features, you agree not to:"
    },
    {
      "kind": "li",
      "text": "Harass, threaten, or abuse other players"
    },
    {
      "kind": "li",
      "text": "Send spam, unsolicited messages, or repetitive content"
    },
    {
      "kind": "li",
      "text": "Share obscene, offensive, or inappropriate content"
    },
    {
      "kind": "li",
      "text": "Impersonate other players or MetaPetal staff"
    },
    {
      "kind": "li",
      "text": "Exploit bugs, glitches, or vulnerabilities for unfair advantage"
    },
    {
      "kind": "li",
      "text": "Use third-party tools, bots, or scripts to automate gameplay"
    },
    {
      "kind": "li",
      "text": "Attempt to access other players' accounts or data"
    },
    {
      "kind": "p",
      "text": "We reserve the right to moderate content and take action — including warnings, temporary suspensions, or permanent bans — against players who violate these rules. In Decentraland, Decentraland's own terms and community rules also apply to your conduct, including in voice and text chat."
    },
    {
      "kind": "h2",
      "text": "5. AI-Generated Content"
    },
    {
      "kind": "p",
      "text": "The Game uses artificial intelligence (xAI Aurora) to generate botanical specimen artwork and planetary visuals. AI-generated content is created procedurally based on in-game traits and does not incorporate personal user data. Generated artwork may vary in style and accuracy. MetaPetal does not guarantee that AI-generated content will be free from imperfections. AI-generated content within the Game is provided for entertainment purposes as part of the game experience."
    },
    {
      "kind": "h2",
      "text": "6. Intellectual Property"
    },
    {
      "kind": "p",
      "text": "All content in the Game — including game design, code, artwork, sound, text, and the Galaxy Gardeners name and branding — is owned by or licensed to MetaPetal and is protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works from the Game's content without prior written permission. Screenshots and gameplay recordings for personal, non-commercial use (such as social media posts) are permitted."
    },
    {
      "kind": "h2",
      "text": "7. Termination"
    },
    {
      "kind": "p",
      "text": "You may stop using the Game at any time. In the iOS app you may delete your account from the Settings menu; if you play in Decentraland, you can request deletion by emailing us with your wallet address. Deletion permanently removes all associated data from our servers. We may suspend or terminate your access to the Game at our discretion if you violate these Terms or engage in conduct we determine to be harmful to other players or the service. Upon termination, your license to use the Game is revoked."
    },
    {
      "kind": "h2",
      "text": "8. Disclaimers"
    },
    {
      "kind": "p",
      "text": "The Game is provided \"as is\" and \"as available\" without warranties of any kind, express or implied. We do not guarantee that the Game will be uninterrupted, error-free, or free of harmful components. We are not responsible for any loss of game progress, virtual items, or data resulting from technical issues, service outages, or account termination. We do not operate Decentraland, the Polygon network, or your wallet, and are not responsible for their availability or for losses arising from them. To the maximum extent permitted by applicable law, MetaPetal's total liability for any claim arising from your use of the Game is limited to the amount you paid for purchases in the Game in the 12 months preceding the claim, or $50, whichever is greater."
    },
    {
      "kind": "h2",
      "text": "9. Governing Law"
    },
    {
      "kind": "p",
      "text": "These Terms are governed by and construed in accordance with applicable law. Any disputes arising from these Terms or your use of the Game will be resolved through good-faith negotiation first, and if necessary, through binding arbitration or the courts of competent jurisdiction."
    },
    {
      "kind": "h2",
      "text": "10. Contact Us"
    },
    {
      "kind": "p",
      "text": "For questions about these Terms: support@galaxygardeners.app"
    }
  ]
}

export const PRIVACY: LegalDoc = {
  "url": "https://galaxygardeners.app/privacy-policy",
  "blocks": [
    {
      "kind": "h1",
      "text": "Privacy Policy"
    },
    {
      "kind": "updated",
      "text": "Last updated: September 26, 2026"
    },
    {
      "kind": "h2",
      "text": "Overview"
    },
    {
      "kind": "p",
      "text": "Galaxy Gardeners (\"the Game\") is developed by MetaPetal. You can play it in the Galaxy Gardeners iOS app or in Decentraland. This policy explains how we collect, use, and protect your information on both."
    },
    {
      "kind": "h2",
      "text": "Information We Collect"
    },
    {
      "kind": "p",
      "text": "Account Information (iOS): When you sign in with Apple or email, we store your authentication ID, username, and friend code. Apple Sign In may share your email if you choose."
    },
    {
      "kind": "p",
      "text": "Account Information (Decentraland): When you play in Decentraland, we receive your wallet address and your Decentraland display name from Decentraland, and link your game account to that wallet address. We do not receive your email address, and we never have access to your wallet's private keys."
    },
    {
      "kind": "p",
      "text": "Gameplay Data: Your game progress including discovered systems, specimens, ship status, expeditions, purchases, and game settings (such as your map and camera preferences) are stored on our servers."
    },
    {
      "kind": "p",
      "text": "Chat Messages: Direct messages and station chat in the iOS app are stored to deliver them to recipients. Messages are filtered for profanity server-side."
    },
    {
      "kind": "p",
      "text": "STEM Questions: Questions you ask STEM, the ship's assistant, are logged without your account ID or wallet address so we can improve its answers."
    },
    {
      "kind": "p",
      "text": "Purchase History: For purchases in the iOS app we record App Store transaction IDs. For purchases paid in MANA in Decentraland we record the transaction hash, the wallet it was sent from, and the amount. We use these records for fulfillment and support."
    },
    {
      "kind": "h2",
      "text": "AI-Generated Content"
    },
    {
      "kind": "p",
      "text": "The Game uses AI image generation services (xAI Aurora) to create botanical specimen and planetary artwork. Only procedural trait descriptions (atmosphere, temperature, soil type, etc.) and base reference images are sent to generate images. No personal user data — including your username, account ID, wallet address, location, or any identifying information — is transmitted to AI providers."
    },
    {
      "kind": "h2",
      "text": "How We Use Your Information"
    },
    {
      "kind": "li",
      "text": "To provide and maintain the game experience"
    },
    {
      "kind": "li",
      "text": "To enable multiplayer features (chat, friends, trading, rescue)"
    },
    {
      "kind": "li",
      "text": "To process and verify purchases"
    },
    {
      "kind": "li",
      "text": "To generate specimen artwork via AI"
    },
    {
      "kind": "li",
      "text": "To improve STEM's answers"
    },
    {
      "kind": "li",
      "text": "To moderate content and enforce community standards"
    },
    {
      "kind": "h2",
      "text": "Data Sharing"
    },
    {
      "kind": "p",
      "text": "We do not sell your personal information. Your data may be shared with:"
    },
    {
      "kind": "li",
      "text": "Apple: For authentication and in-app purchase processing in the iOS app"
    },
    {
      "kind": "li",
      "text": "Polygon network: To verify a MANA payment, we look up its transaction on the public Polygon blockchain through a blockchain data provider. Blockchain transactions, including your wallet address, are public by nature."
    },
    {
      "kind": "li",
      "text": "xAI: Procedural trait descriptions and base reference images only (no personal data)"
    },
    {
      "kind": "li",
      "text": "Supabase: Our database and authentication provider"
    },
    {
      "kind": "li",
      "text": "AWS: For image storage and delivery (CloudFront CDN)"
    },
    {
      "kind": "p",
      "text": "In Decentraland, your avatar, voice chat, and text chat are provided by Decentraland, not by us, and are covered by Decentraland's own privacy policy. Other players in Decentraland can see your display name and avatar."
    },
    {
      "kind": "h2",
      "text": "Data Retention & Deletion"
    },
    {
      "kind": "p",
      "text": "Your data is retained as long as your account is active. In the iOS app you can delete your account at any time from Settings. If you play in Decentraland, email us from any address with your wallet address to request deletion; we may ask you to prove you control the wallet. Account deletion permanently removes all your data from our servers, including game progress, messages, and purchase records. MANA transactions recorded on the Polygon blockchain are public and permanent, and cannot be deleted by us or anyone else."
    },
    {
      "kind": "h2",
      "text": "Children's Privacy"
    },
    {
      "kind": "p",
      "text": "Galaxy Gardeners includes chat features and purchases. We do not knowingly collect personal information from children under 13. The iOS app's age rating reflects its interactive features."
    },
    {
      "kind": "h2",
      "text": "Your Rights"
    },
    {
      "kind": "p",
      "text": "You have the right to:"
    },
    {
      "kind": "li",
      "text": "Access your data (viewable in the Game)"
    },
    {
      "kind": "li",
      "text": "Delete your account and all associated data"
    },
    {
      "kind": "li",
      "text": "Block other players from contacting you (in the iOS app)"
    },
    {
      "kind": "li",
      "text": "Report abusive content"
    },
    {
      "kind": "h2",
      "text": "Contact Us"
    },
    {
      "kind": "p",
      "text": "For privacy questions, concerns, or deletion requests: support@galaxygardeners.app"
    }
  ]
}

